server:
  port: 9011 #configurar numero de puerto
   
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/ligas
    #username: roger
    #password: empresa
    
    url: jdbc:mysql://wager8ligas.db.10711341.hostedresource.com:3306/wager8ligas
    username: wager8ligas
    password: C9cf25!0cc2bf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #comprueba con cada restart del server si los modelos corresponden con las tablas, si no, hace el update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy # dialectos para la consulta
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 